/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniComplexExample */

#ifndef _Included_JniComplexExample
#define _Included_JniComplexExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniComplexExample
 * Method:    init_native_resources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniComplexExample_init_1native_1resources
  (JNIEnv *, jclass);

/*
 * Class:     JniComplexExample
 * Method:    recall_objects
 * Signature: ()[LNameWithInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_JniComplexExample_recall_1objects
  (JNIEnv *, jclass);

/*
 * Class:     JniComplexExample
 * Method:    register_object
 * Signature: (LNameWithInfo;)V
 */
JNIEXPORT void JNICALL Java_JniComplexExample_register_1object
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
