/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniExample */

#ifndef _Included_JniExample
#define _Included_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniExample
 * Method:    native_call
 * Signature: (LJniExample;)V
 */
JNIEXPORT void JNICALL Java_JniExample_native_1call
  (JNIEnv *, jclass, jobject);

/*
 * Class:     JniExample
 * Method:    org_native_call
 * Signature: (LJniExample;)V
 */
JNIEXPORT void JNICALL Java_JniExample_org_1native_1call
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
